#!/bin/bash

#Set up the repository name
read -p "Name your repository: " repository
#Exit if the directory already exists
if [ -d "$repository" ]; then
  echo "Directory exists! Pick a new name."
  exit 1
fi
mkdir $repository
cd $repository

#Initialize as a Git repo
read -p "Branch name? " git_branch
git init -b $git_branch

#Add a README file
echo "# $repository
This repository was generated by usmcamgrimm's scaffolding script." >> README.md

#Add a .gitignore file
cat <<-EOF > .gitignore
# Ignore bundler config.
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3
/db/*.sqlite3-*

# Ignore all logfiles and tempfiles.
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep

# Ignore pidfiles, but keep the directory.
/tmp/pids/*
!/tmp/pids/
!/tmp/pids/.keep

# Ignore uploaded files in development.
/storage/*
!/storage/.keep
/tmp/storage/*
!/tmp/storage/
!/tmp/storage/.keep

/public/assets

# Ignore master key for decrypting credentials and more.
/config/master.key

node_modules/
EOF

#Stage files and commit
git add .
git commit -m "Initial commit for new repository"

#Add the remote
read -p "What is your GitHub username? " username
git remote add origin git@github.com:$username/$repository.git

#Push the new repository to GitHub
git push --set-upstream origin $git_branch

echo "Your new repository is here: https://github.com/$username/$repository"
echo "SFMF!"